### ISSUE TITLE
Add information on which card is timer running

### ISSUE THREAD

**Issue by MatejSz** [danniehansen/activity-timer#101]
We have many cards on our Trello board (hundreds).

Sometimes is hard to see on which card currently activity timer is running.

1) We would appreciate it if there would be a place on the Trello board where the user can see where(which card) his activity timer is running.

2) Sometimes we switch between boards and forget to turn off the timer on the board that we switch from and turn on another timer on the board that we switch to. In such cases, the timer is running on two boards in the same time. For this reason, we would appreciate very much to see on what cards the activity timer is running across all the boards that the user is a member of.

**Comment by danniehansen** [comment]
Hi @MatejSz,

Thank you once again for the excellent feature requests. I like the idea. If you have a cluttered boards then it can be hard to get an exact overview.

I'll try to see if it's possible to interact with cards on a different board, or read the data from other boards. I'm fairly sure this cannot be done through the existing API since they're in essence two different PowerUps with their own data on their respective board. However, what we could do is to utilize client-side storage to just help give an indication if timers are running on other boards. While this wouldn't be able to give you much information besides that you have a timer running on a different board, maybe that would just be enough?

I'm picturing a board button under the 'Activity timer' board button that is displayed with a clock if there is a timer running. Clicking it will then open an overview over which timers are currently running, and indicate if some of them are from remote boards. Timers on the same board as you're viewing now can then be stopped right there. Where-as timers on remote boards will when clicked link to the remote board & from there user can de-activate using the same model on that board.

What do you think of the above`? Keen to hear your thoughts.

**Comment by MatejSz** [comment]
Sounds good Dannie.
The board button under the Activity timer would be perfect.
Thank you for your suggestions.

**Comment by MatejSz** [comment]
Hi @danniehansen ,
   may I ask, approximately when you think will you implement this feature?
Thank you very much for you work

**Comment by danniehansen** [comment]
Hi @MatejSz,

We've recently moved into a newly purchased house that has taken up a lot of time. I'm planning to have a full day of working with Activity timer early next month once we're more settled. So I'm hoping to do some investigation into this early next month, and maybe land the feature mid next month.

**Comment by danniehansen** [comment]
Hi @MatejSz,

I've spent some time looking into it and come to the conclusion that it's technically possible to make a shacky solution for the cross-board tracking display. But the challenge is that the solution would only work on 1 device. If you swapped devices while tracking it would loose the information, or if you started tracking on another device while viewing on a 2nd - then it would also disconnect since it's two separate devices. This would be bad for UX as there would be many cases where users would see timers running when they weren't, or they would just in general see a wrong state.

Initially i checked to see if i could read the data cross-boards. This i could in theory. But would require users to grant API access like with the report feature. Since this would be a more broadly used feature, then i think this would be introducing complexity where it isn't needed.

But, that being said. I will this Sunday be looking at introducing the board button discussed just for timers on the current board you're on. Then it's much easier to at least screen your boards and see if any have active timers running.

I'm hoping to have development done this Sunday and available to testing early next week.

**Comment by ERwoodside** [comment]
Very interested in this feature @MatejSz @danniehansen

**Comment by danniehansen** [comment]
@ERwoodside @MatejSz 

I've just pushed a release that introduces a new board button contextmenu item that indicates if a timer is running or not. Clicking it will open the card that you have an active timer running on.

This is the best i can do since i cannot live update the board button it-self. Keen to hear your thoughts on it.

**Comment by MatejSz** [comment]
Hi @danniehansen 
Thank you very much, is it already in production?
I can not find this context menu button in our Trello.

**Comment by ERwoodside** [comment]
@danniehansen This works well! I was able to drop down the power up, locate
the running timer, and deactivate the timer.  My wish would be for a timer
icon to appear next to the power up IF the timer was running for a quick
visual. The icon is currently black, but it could be red if a timer was
running.


Jodi Woodside
Director of Development & Operations | Elite Research, LLC
Project Manager | Divergent Web Solutions, LLC
9901 Valley Ranch Pkwy. E., Ste. 2035, Irving, TX 75063
Phone: 972-538-1374 | 1-800-806-5661 ext. 714
www.eliteresearch.com | www.divergentwebsolutions.com
Fax: 1-800-806-5661 | ***@***.***
LinkedIn: https://www.linkedin.com/in/jodiwoodside/

*Note*:  All e-mails and files transmitted from Elite Research, LLC may
contain PRIVILEGED or CONFIDENTIAL information and may be used only by the
intended recipient.  Any use - dissemination, distribution, forwarding,
printing or copying of e-mails or any files (including templates) is
strictly prohibited.

**Comment by danniehansen** [comment]
@MatejSz yeah, you properly just need to clear your browser cache. I've also taken steps in this release to reduce the issues with new releases and browser cache. Now browser should hold no cache & get a fresh version on every pageload. The new item is added under the board button at the top-right corner of your trello board.

@ERwoodside Great! Glad to hear it worked. That was also the desired implementation. Unfortunately, due to Trello API restrictions it's not possible for me to update the board button when timers start or even periodically do it. The board button is static and only items shown when clicking it can be loaded in when clicked.

I'm closing the issue for now. As this should cover the original request. @MatejSz - if you feel like there is more to the existing issue, please just comment and reopen.
