### ISSUE TITLE
TIME STAMP!

### ISSUE THREAD

**Issue by SmokekingLV** [danniehansen/activity-timer#120]
Hey guys. So I've discovered Trello, and its amazing. It's literally everything I need. ALMOST. 

I need a time stamp on the card for a quick glance, and I also have some rules that I need to go a little bit deeper. 

I've done as much research as I can and I can't find any sort of a work around. SO, here we are. I'm using this for day to day management of a multi location business. 

Issue 1. Time Stamps- As far as I can see the only answer Trello will give in regards to a time stamp, is to open up the card, scroll all the way to the bottom, and push a button. That just isn't acceptable lol. I need a time stamp to be visible when the card moves with out clicking it. My boss needs this info at a glance. I'm doing my best to compartmentalize the flow. 

Archived items.. There is no way to search by date, there is no way to see the date out in the open on the card. I need to be able to choose a date range for the date archived, and have that visible on the card , maybe in the title or something. 

Issue 2 Check lists.  My thoughts and action plan was to create a check list , when the item is checked on the checklist, it will transfer that item,  with the item name , to the next list in line. That way those items can be view and checked off by the next level. 

Issue 3. CSV.. what the shit is happening , i need a way more detailed report. 

Maybe I'm expecting to much out of the app, or maybe I'm just not as familiar as i though I was. But I can't figure this out , and I am 99% sure that its just not possible with in the app as it stands. It would be incredible if that could change. 

Thanks , not sure if this even the proper route at this just taking a stab in the dark.

**Comment by danniehansen** [comment]
Hi @SmokekingLV,

Issue 1: I don't exactly how what you mean with timestamps here. We indicate on the board the time spent along with the estimate. Since cards can be worked on across multiple days, weeks or months - then there is little incentive to show any other details.

I'm not sure what you mean about archived items. The powerup does not provide the ability to archive trackings. We do however fetch both open and archived cards in the data exporters. But unless you're getting a premium subscription then filtering here has to be done in excel. Premium includes date from/to filtering options there.

Issue 2: I don't see the connection here to time tracking. Can you please elaborate.

Issue 3: CSV is universal. I'm not personally going to invest in adding other file formats and you can quite easily open CSV in excel and save it in any other format if you require it. But feel free to send a PR to include it yourself 👍

**Comment by SmokekingLV** [comment]
I appreciate the reply . I did a little more digging and figured out I was
not as familiar with this product as I thought I was. This was most
certainly a premature email on my part and I apologize for wasting your
time.
