### ISSUE TITLE
Timer Ends When Card Moves List

### ISSUE THREAD

**Issue by Checkmate363** [danniehansen/activity-timer#22]
When I have an active timer and move the card between lists, the timer ends. Is this intended?

**Comment by danniehansen** [comment]
Hi @Checkmate363 

Yeah - this is the intended functionality. The reason behind it was that in the early stages of tested with a few users we saw that users often forgot to stop the timer. Because of this and that typical workflows have a in progress list for card we saw this as a way of mitigating the issue.

I could add a setting for this so that users can disable this behavior globally on the power-up - thoughts?

**Comment by Checkmate363** [comment]
A setting would be nice. I tend to start the timer when my card is in my "Today" list and then move it to "Doing Now", rather then the other way around.

**Comment by danniehansen** [comment]
@Checkmate363 Alrighty. Got it. I agree - a setting would be nice. I'm adding this for the next release in two weeks. Might be before, depends on if i can find a free evening to work on it.

**Comment by danniehansen** [comment]
@Checkmate363 I've added a new 'Settings' button under the card buttons that allows you to toggle this feature. Also have another feature in progress that allows you to move the card to a list of your choice when you start tracking. More on this later today :)

**Comment by Checkmate363** [comment]
@danniehansen Awesome. And I love the idea of the autostart timer when I move cards to some sort of "doing now" list.
