### ISSUE TITLE
Minute/Hour summary + shortening at the `Manage time` card on each entry

### ISSUE THREAD

**Issue by jonez1** [danniehansen/activity-timer#29]
Hello Dannie,
first of all, thank you for your trello power up.

I was thinking about some little update to `Manage time` card entries.
1) It would be nice to have there after the time range some kind of summary in minutes or hours (see the screenshot).
![obrazek](https://user-images.githubusercontent.com/33315573/106152081-52a0ac80-617d-11eb-8725-6405e085fcdf.png)

2) When the time interval is on the same day, the repetition of the date could be ommited, which could lead to more clarity.
I admit, that when you'll have those "shortened" and "unshortened" lines under, but i think is't worth the shot.
![obrazek](https://user-images.githubusercontent.com/33315573/106152810-25a0c980-617e-11eb-82ad-392c2a3776f9.png)
![obrazek](https://user-images.githubusercontent.com/33315573/106153311-b2e41e00-617e-11eb-83ac-63e51ea8d27b.png)

I think i could prepare a pull request if you would find those things usefull.

**Comment by danniehansen** [comment]
Hi @jonez1 

Really interesting feedback. I love both suggestions. 

I think minutes would be a good addition. We could do '1h 2m' to shorten it down even more and allow for hours to be displays? What's to note about this display is that it's a Trello component - so the only thing that we can change is the actual text.

Which is why this tied greatly into your 2nd suggestion. Most tracking's is within the same date. Meaning there is much room to save by omitting the date.

I would love both additions. & a PR would be much appreciated if you're able to wrap your head around my source code. It's a bit messy unfortunately 😄

**Comment by jonez1** [comment]
I've made the changes, it was quite straightforward. It should work as suggested.
The only thing i couldn't do is to test it in the Trello environment. Is there a way to test it?

**Comment by danniehansen** [comment]
@jonez1 Your PR was merged. I'll close this issue on this note. Thank you for looking into this optimization :)
