### ISSUE TITLE
Add time manually

### ISSUE THREAD

**Issue by Attacler** [danniehansen/activity-timer#38]
Can you make a way to enter time manually?
Basicly i had another extension first that would track the time for me but it did not fully meet my requirements.
This extension does, but sometimes when you forget to start the timer, you cannot enter (for example) an hour on your own.

**Comment by danniehansen** [comment]
Hi Attacler,

Manually adding time is possible - just a bit clunky. If you start and stop the timer right away - then you can just modify that 1 second timeslot to whatever manually registered time you want to register :) That's how I've been doing it.

I'll leave the issue open. Because while there is a work-around - it would be nice to actually have a feature implemented for this.

**Comment by danniehansen** [comment]
@Attacler Added 'Add manually' option under 'Manage time' when you have at least 1 tracking. The UI is a bit janky - but it's what we can do with Trello's built in UI :)
