### ISSUE TITLE
It's not possible to make a total summary of estimate in one column

### ISSUE THREAD

**Issue by MatejSz** [danniehansen/activity-timer#51]
It's not possible to make a total summary of estimates in one column.

For planning the sprint It would be very beneficial if we could see sum of all estimates in one column.
Now we can only see the estimation of separate tasks and we have to sum the total time of all tasks by calculator or external program.

**Comment by danniehansen** [comment]
@MatejSz 

First. Sorry for the late reply. Haven't notices the notifications about these issues.

Recently we switched internally to use SCRUM and quickly realized this very same thing. Unfortunately there is no easy way of implementing this as Trello's API is rather limited. I'm not able to inject anything in on the overlay of cards other than a button up top like "Activity timer history" or the badges you see on the cards.

What could make sense for us is to implement the ability under "Activity timer history" to flip between showing time tracked & estimates. Then with a different view we could display the estimates and allow for filtering by e.g. list.

Would this be something you'd be interesting in seeing?

**Comment by MatejSz** [comment]
Hello @danniehansen,
we were talking about this feature in our team and we would be happy if you could Implement suggested ability:
 "Activity timer history" to flip between showing time tracked & estimates.
 
 Thank you very much we really appreciated it.

**Comment by danniehansen** [comment]
@MatejSz 

Sounds great. I'm not sure when I will be able to implement this or in what variant it will be implemented. But I will keep you posted here on the issue.

**Comment by MatejSz** [comment]
@danniehansen 

Thank you very much, Dannel. 
We'll wait for your message here ;).

Have a great day

**Comment by danniehansen** [comment]
@MatejSz Update. Please see https://github.com/danniehansen/activity-timer/issues/52#issuecomment-986272045 - more info will follow once V2.0.0 is out and available.

**Comment by danniehansen** [comment]
@MatejSz Since v2.0.0 has been released I've worked at completely revamping data exporting. It now features estimates and loads of new filtering options. Filtering is however a pro feature - but you can try it out for 7 days for free.

For estimates filtering on estimates it allows you to continuously track how much you've put in for the sprint by having a secondary window open with your filtering on for which lists to take into consideration. Then every time you move a card over from your backlog into the sprint you can in the other window with the data exporting tool just click 'Refresh'. I'll then fetch the latest data from Trello & show new cards in the list. Down at the bottom right I'll show a complete sum of the estimates.

This should hopefully help scrum masters plan their sprints using Activity timer.

Let me know what you think & if you have any feedback :)

**Comment by MatejSz** [comment]
Thank you very much @danniehansen .
We'll try it ;).

Have a nice day
