### ISSUE TITLE
Extract total estimate time 

### ISSUE THREAD

**Issue by TinaKaltoft3** [danniehansen/activity-timer#52]
Hi 
Is it possible to make an extract where the total estimate time is visible 

and 

If two of my team-members have worked on a card - I can't se both name in the csv-fil - am I doing something wrong? Or is it not possible?

Kind Regards Tina

**Comment by danniehansen** [comment]
Hi @TinaKaltoft3 

Sorry for the late reply. Missed I had notifications about this.

It will actually if multiple team members have tracked time on the same card create a row for each members tracking's in the "Export to CSV" function under 'Activity timer history'.

Is this what you're looking for?

**Comment by TinaKaltoft3** [comment]
Hi Daninie 

No worries 
Yes i think that would solve my problem 

New Q - is it possible to extract 'Total estimated time' pr. card??

**Comment by danniehansen** [comment]
@TinaKaltoft3 Just a heads-up. This will be planned into the next release (V2.0.1) of Activity timer & will be available on the Pro version (more coming in a day or so). V2.0.0 will be out soon & feature a complete rewrite of Activity timer. This will allow for faster progress on new features. Will keep you posted here on this when I know more.

**Comment by danniehansen** [comment]
@TinaKaltoft3 Since V2.0.0 I've worked heavily on data exporting & completely overhauled the old exporter. This now also features a estimate data exporter for you to export estimates with various filtering and group by features.

The filtering part is all part of the new pro plan. But you can still export everything on the free plan. If you'd like to try the pro plan you can do so for 7 days for free. Then you can view the new filtering for estimates data exporter.

Let me know if this functionality was what you thought of & if it helps accommodate your request.
