### ISSUE TITLE
Start/Stop Timer When Card is Open/Closed

### ISSUE THREAD

**Issue by RomainH4890** [danniehansen/activity-timer#65]
Hello Dannie,

Would it be possible to start the timer as soon as a card is open ? 
And to stop the timer as soon as a card is closed ? 

Even if this is not the standard behaviour, it could be an option which could be chosen in the power-up parameters.

**Comment by danniehansen** [comment]
Hi @RomainH4890,

Appreciate the feature request!

I do think it is possible to make. Just not sure how easy it would be.

Also not entirely sure how well that fits with my vision of Activity timer. I want to ensure that i do not include too niche items that make it fell bloated. But i will however keep the discussion open by leaving the issue here. Then if others fell like this would really be helpful, they can add their opinions here. Then with time it'll tell if this might be a requested feature by a larger crowd.

**Comment by RomainH4890** [comment]
Hello Dannie,

Thank you for your answer.

I have been using your power-up for some days now, and I find it could really provide some interesting datas.
I chose it over other solutions, because of it simplicity (others are too complex and visible, yours is discret as it needs to be).

But I too often forget to start or stop the timer during my work, and even when I do it, it represent a tedious task to do each time I act on a card, so it becomes counterproductive.

It would be really really powerful if timer was starting and stoping automatically each time a card was open or closed.

This way we wouldn't have to click on the timer button at all, except to remove false time due to a card which has stayed open by mistake.
I think, the more a solution works by itself, the more it becomes powerful.

So having this feature could only be a great asset to those in need to track their productivity :-)

Have a great day and thank you for your work.

**Comment by danniehansen** [comment]
Hi @RomainH4890,

I know it has been a while. I'm considering revisiting this & see what it possible. I'm not 100% convinced that this will work as UX will be hard to work out with the way that powerups are working within Trello. If this is to be made, then it needs to be made right & just make sense. If there is too many edge cases where it does not track properly if where users do not entirely understand what is going on. Then i may not consider it for release. However, if it proves to be a possibility - the I'll put it under a 'beta' flag so that it can be deprecated and removed again if we receive too many complaints about it not working as expected.

**Comment by danniehansen** [comment]
Adding to version 2.2 release candidate for next week.

**Comment by RomainH4890** [comment]
Hello Dannie,


Thank you for reaching out to give me this info.


Could you please confirm to me when it will be available please ?
I will give it another try and let you know how it goes for me.




Another thing : 
I can't find my "sent messages" to you.
Could you send them back to me please ?




Looking Forward to hearing from you.


Have a great day.


Best Regards,




Romain HAYOT
Martinique - 97240
+596 (0) 696 10 10 20
***@***.*** ***@***.***


[data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs=3D]
Le ven. 22 juil. 2022 à 16:19, Dannie Hansen ***@***.***> a
écrit :

**Comment by danniehansen** [comment]
Hi @RomainH4890,

I don't have an ETA on when it will be publicly available. I will try to get a tech-demo ready of it this week. Then maybe next week it could be released and made available if it proves to work nicely.

Regarding the messages. I'm not sure, all I got from you is this issue.

**Comment by danniehansen** [comment]
Hi @RomainH4890,

Unfortunately i didn't get around to attempting this for 2.2. I'll be postponing this for 2.3. I'll keep you posted.

**Comment by danniehansen** [comment]
Hi @RomainH4890,

I never managed to get anything working that resembled something i would consider to release. There is simply too many constraints with the current powerup system that would allow us to do just this.

So i will be closing the issue for now. Appreciate the suggestion originally, sorry for not getting back earlier.
