### ISSUE TITLE
Data exporter - Estimates - does not show all tasks with a filled estimate

### ISSUE THREAD

**Issue by MatejSz** [danniehansen/activity-timer#73]
Data exporter - Estimates - does not show all tasks with a filled estimate.

**Steps to reproduce:**
1) Trello: Activity timer - Data exporter - Estimates
2) We filter by Lists=SPRINT BACKLOG (one of our Trello columns)
3) Then we incorrectly don't see all the tasks in column "SPRINT BACKLOG" although the tasks have filled the estimate.
(we don't see about half of our tasks)

Unfortunately, we can not tell why some tasks are displayed and some are missing in "Activity timer - Data exporter - Estimates".
Task seems very similar.

**Comment by danniehansen** [comment]
Hi @MatejSz,

That's really strange! Thank you for bringing this to my attention. I'll have a look at this, this weekend.

Debugging a Trello powerup that is on close connection with an issue that you're seeing in particular can be quite challenging. As i don't have the same data set. But I'll try to see if i can reproduce this, and if I'm not able to, look over the implementation to see if i can see any obvious flaws that could cause this.

**Comment by danniehansen** [comment]
Hi @MatejSz,

This should be fixed in https://github.com/danniehansen/activity-timer/releases/tag/2.1.1

I was also able to provoke this issue on my old board with many cards with and without trackings / estimates.
Any feedback on the new release would be greatly appreciated. You might need to clear cache in order to get the latest changes. Just FYI.

**Comment by MatejSz** [comment]
Hi @danniehansen .

**Test OK.** Estimates now shows all the tasks with the filled estimate.
Super! Thank you for your fix.
